spring:
  application:
    name: micro-learning-api
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  datasource:
    url: jdbc:postgresql://localhost:5432/practise
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 3000
  servlet:
    context-path: /api/v1

jwt:
  secret: 9f3c8b6a1d4e7f2c9a8b6d4e1f7c3a9b8d6f1e2c4a7b9d5e8f3c1a6b9d2e7f5
  expiration: 604800000  # 7 days in milliseconds

cors:
  allowed-origins: http://localhost:5173

